apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-03d3fda11697d0ea8
