apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0512064892fec5d3d
