apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: expense-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind : Pod
metadata: 
  name: ebs-static
  labels:
    purpose: "ebs-static-demo"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountpath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: expense-claim

          
          
   
