apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: expense-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

# ---
# kind : pod
# apiVersion: v1
# metadata: 
#   name: ebs-static
#   labels:
#     purpose: "ebs-static-demo"
#   spec:
   
